// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.10.0
// source: gRPC/cat.proto

package gRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailMessage) Reset() {
	*x = EmailMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailMessage) ProtoMessage() {}

func (x *EmailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailMessage.ProtoReflect.Descriptor instead.
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{0}
}

func (x *EmailMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrderMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sourcelat  float32 `protobuf:"fixed32,1,opt,name=sourcelat,proto3" json:"sourcelat,omitempty"`
	Sourcelng  float32 `protobuf:"fixed32,2,opt,name=sourcelng,proto3" json:"sourcelng,omitempty"`
	Destlat    float32 `protobuf:"fixed32,3,opt,name=destlat,proto3" json:"destlat,omitempty"`
	Destlng    float32 `protobuf:"fixed32,4,opt,name=destlng,proto3" json:"destlng,omitempty"`
	Pathlength float32 `protobuf:"fixed32,5,opt,name=pathlength,proto3" json:"pathlength,omitempty"`
	Customer   string  `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	Driver     string  `protobuf:"bytes,7,opt,name=driver,proto3" json:"driver,omitempty"`
}

func (x *OrderMessage) Reset() {
	*x = OrderMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMessage) ProtoMessage() {}

func (x *OrderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMessage.ProtoReflect.Descriptor instead.
func (*OrderMessage) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{1}
}

func (x *OrderMessage) GetSourcelat() float32 {
	if x != nil {
		return x.Sourcelat
	}
	return 0
}

func (x *OrderMessage) GetSourcelng() float32 {
	if x != nil {
		return x.Sourcelng
	}
	return 0
}

func (x *OrderMessage) GetDestlat() float32 {
	if x != nil {
		return x.Destlat
	}
	return 0
}

func (x *OrderMessage) GetDestlng() float32 {
	if x != nil {
		return x.Destlng
	}
	return 0
}

func (x *OrderMessage) GetPathlength() float32 {
	if x != nil {
		return x.Pathlength
	}
	return 0
}

func (x *OrderMessage) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *OrderMessage) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type IndicatorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indicator bool `protobuf:"varint,1,opt,name=indicator,proto3" json:"indicator,omitempty"`
}

func (x *IndicatorMessage) Reset() {
	*x = IndicatorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndicatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorMessage) ProtoMessage() {}

func (x *IndicatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorMessage.ProtoReflect.Descriptor instead.
func (*IndicatorMessage) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{2}
}

func (x *IndicatorMessage) GetIndicator() bool {
	if x != nil {
		return x.Indicator
	}
	return false
}

type CodeNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CodeNumber) Reset() {
	*x = CodeNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeNumber) ProtoMessage() {}

func (x *CodeNumber) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeNumber.ProtoReflect.Descriptor instead.
func (*CodeNumber) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{3}
}

func (x *CodeNumber) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TicketMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment     string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Tickettype  string `protobuf:"bytes,2,opt,name=tickettype,proto3" json:"tickettype,omitempty"`
	Responsible string `protobuf:"bytes,3,opt,name=responsible,proto3" json:"responsible,omitempty"`
	Ticketorder string `protobuf:"bytes,4,opt,name=ticketorder,proto3" json:"ticketorder,omitempty"`
}

func (x *TicketMessage) Reset() {
	*x = TicketMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketMessage) ProtoMessage() {}

func (x *TicketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketMessage.ProtoReflect.Descriptor instead.
func (*TicketMessage) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{4}
}

func (x *TicketMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *TicketMessage) GetTickettype() string {
	if x != nil {
		return x.Tickettype
	}
	return ""
}

func (x *TicketMessage) GetResponsible() string {
	if x != nil {
		return x.Responsible
	}
	return ""
}

func (x *TicketMessage) GetTicketorder() string {
	if x != nil {
		return x.Ticketorder
	}
	return ""
}

type BIOscetch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname  string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname   string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Patronymic string `protobuf:"bytes,3,opt,name=patronymic,proto3" json:"patronymic,omitempty"`
}

func (x *BIOscetch) Reset() {
	*x = BIOscetch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BIOscetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BIOscetch) ProtoMessage() {}

func (x *BIOscetch) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BIOscetch.ProtoReflect.Descriptor instead.
func (*BIOscetch) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{5}
}

func (x *BIOscetch) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *BIOscetch) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *BIOscetch) GetPatronymic() string {
	if x != nil {
		return x.Patronymic
	}
	return ""
}

type BIOscetchWithEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Firstname  string `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname   string `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Patronymic string `protobuf:"bytes,3,opt,name=patronymic,proto3" json:"patronymic,omitempty"`
	Email      string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *BIOscetchWithEmail) Reset() {
	*x = BIOscetchWithEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BIOscetchWithEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BIOscetchWithEmail) ProtoMessage() {}

func (x *BIOscetchWithEmail) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BIOscetchWithEmail.ProtoReflect.Descriptor instead.
func (*BIOscetchWithEmail) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{6}
}

func (x *BIOscetchWithEmail) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *BIOscetchWithEmail) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *BIOscetchWithEmail) GetPatronymic() string {
	if x != nil {
		return x.Patronymic
	}
	return ""
}

func (x *BIOscetchWithEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrderNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ordernumber string `protobuf:"bytes,1,opt,name=ordernumber,proto3" json:"ordernumber,omitempty"`
}

func (x *OrderNumber) Reset() {
	*x = OrderNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gRPC_cat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderNumber) ProtoMessage() {}

func (x *OrderNumber) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_cat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderNumber.ProtoReflect.Descriptor instead.
func (*OrderNumber) Descriptor() ([]byte, []int) {
	return file_gRPC_cat_proto_rawDescGZIP(), []int{7}
}

func (x *OrderNumber) GetOrdernumber() string {
	if x != nil {
		return x.Ordernumber
	}
	return ""
}

var File_gRPC_cat_proto protoreflect.FileDescriptor

var file_gRPC_cat_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x24, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xd2, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x6c, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6c,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x6c, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x6c, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x6c, 0x61, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x6c, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x6c, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x68, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x70, 0x61, 0x74,
	0x68, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x10, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x20, 0x0a,
	0x0a, 0x43, 0x6f, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x8d, 0x01, 0x0a, 0x0d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0x65, 0x0a, 0x09, 0x42, 0x49, 0x4f, 0x73, 0x63, 0x65, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x0a, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6e,
	0x79, 0x6d, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x74, 0x72,
	0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x42, 0x49, 0x4f, 0x73, 0x63,
	0x65, 0x74, 0x63, 0x68, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x72, 0x6f,
	0x6e, 0x79, 0x6d, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x74,
	0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2f, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xa7,
	0x03, 0x0a, 0x04, 0x54, 0x61, 0x78, 0x69, 0x12, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0d, 0x2e,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x2e, 0x42,
	0x49, 0x4f, 0x73, 0x63, 0x65, 0x74, 0x63, 0x68, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x42, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0d,
	0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x2e,
	0x42, 0x49, 0x4f, 0x73, 0x63, 0x65, 0x74, 0x63, 0x68, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x0c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x0d, 0x2e,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x2f,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x0c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x0d,
	0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0b, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x0e, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x12, 0x13, 0x2e, 0x42, 0x49, 0x4f, 0x73, 0x63, 0x65, 0x74, 0x63, 0x68, 0x57, 0x69, 0x74,
	0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x11, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x42, 0x49,
	0x4f, 0x73, 0x63, 0x65, 0x74, 0x63, 0x68, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x1a, 0x11, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x52,
	0x50, 0x43, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gRPC_cat_proto_rawDescOnce sync.Once
	file_gRPC_cat_proto_rawDescData = file_gRPC_cat_proto_rawDesc
)

func file_gRPC_cat_proto_rawDescGZIP() []byte {
	file_gRPC_cat_proto_rawDescOnce.Do(func() {
		file_gRPC_cat_proto_rawDescData = protoimpl.X.CompressGZIP(file_gRPC_cat_proto_rawDescData)
	})
	return file_gRPC_cat_proto_rawDescData
}

var file_gRPC_cat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gRPC_cat_proto_goTypes = []interface{}{
	(*EmailMessage)(nil),       // 0: EmailMessage
	(*OrderMessage)(nil),       // 1: OrderMessage
	(*IndicatorMessage)(nil),   // 2: IndicatorMessage
	(*CodeNumber)(nil),         // 3: CodeNumber
	(*TicketMessage)(nil),      // 4: TicketMessage
	(*BIOscetch)(nil),          // 5: BIOscetch
	(*BIOscetchWithEmail)(nil), // 6: BIOscetchWithEmail
	(*OrderNumber)(nil),        // 7: OrderNumber
}
var file_gRPC_cat_proto_depIdxs = []int32{
	0, // 0: Taxi.GetCustomerByEmail:input_type -> EmailMessage
	0, // 1: Taxi.GetDriverByEmail:input_type -> EmailMessage
	7, // 2: Taxi.GetCustomerEmail:input_type -> OrderNumber
	7, // 3: Taxi.GetDriverEmail:input_type -> OrderNumber
	3, // 4: Taxi.GetTicketInfo:input_type -> CodeNumber
	6, // 5: Taxi.CreateCustomer:input_type -> BIOscetchWithEmail
	6, // 6: Taxi.CreateDriver:input_type -> BIOscetchWithEmail
	1, // 7: Taxi.CreateOrder:input_type -> OrderMessage
	5, // 8: Taxi.GetCustomerByEmail:output_type -> BIOscetch
	5, // 9: Taxi.GetDriverByEmail:output_type -> BIOscetch
	0, // 10: Taxi.GetCustomerEmail:output_type -> EmailMessage
	0, // 11: Taxi.GetDriverEmail:output_type -> EmailMessage
	4, // 12: Taxi.GetTicketInfo:output_type -> TicketMessage
	2, // 13: Taxi.CreateCustomer:output_type -> IndicatorMessage
	2, // 14: Taxi.CreateDriver:output_type -> IndicatorMessage
	2, // 15: Taxi.CreateOrder:output_type -> IndicatorMessage
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_cat_proto_init() }
func file_gRPC_cat_proto_init() {
	if File_gRPC_cat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gRPC_cat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndicatorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BIOscetch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BIOscetchWithEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gRPC_cat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gRPC_cat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_cat_proto_goTypes,
		DependencyIndexes: file_gRPC_cat_proto_depIdxs,
		MessageInfos:      file_gRPC_cat_proto_msgTypes,
	}.Build()
	File_gRPC_cat_proto = out.File
	file_gRPC_cat_proto_rawDesc = nil
	file_gRPC_cat_proto_goTypes = nil
	file_gRPC_cat_proto_depIdxs = nil
}
